### ISSUE TITLE
添加查询接口

### ISSUE THREAD

**Issue by pysio2007** [ItzGreenCat/Antimony-SkyBlock#19]
Uh 当队伍有高能玩家自动报警，数据来源：“网站搭建中”

**Comment by pysio2007** [comment]
https://black.maid.ink/

**Comment by Jrojro728** [comment]
网站有api吗？

**Comment by pysio2007** [comment]
api.scamlist.cn/uuid/{uuid}.json
例如:https://api.scamlist.cn/uuid/0b524cc5edb745d1ba3b675e15079137.json
@Jrojro728

**Comment by Jrojro728** [comment]
hmm，看起来直接用我之前用的gson框架就可以检测，主要是游戏内的UUID获取，让 @ItzGreenCat 去做awa

**Comment by pysio2007** [comment]
主要是我懒病犯了，不然我写了（

**Comment by pysio2007** [comment]
#22
