### ISSUE TITLE
4k分辨率下游戏在左下角，正常吗？

### ISSUE THREAD

**Issue by Jrojro728** [ItzGreenCat/Antimony-SkyBlock#20]
如题

**Comment by pysio2007** [comment]
能否提供视频、图片，或更具体的描述

**Comment by Jrojro728** [comment]
![image](https://user-images.githubusercontent.com/64339010/198827957-d924b357-2ee3-4754-8e92-4b67613844b9.png)

**Comment by pysio2007** [comment]
这一般是由错误的分辨率设置，或者JAVA未能识别到正确的分辨率导致的，可以尝试使用Zulu JDK:https://cdn.azul.com/zulu/bin/zulu8.66.0.15-ca-jdk8.0.352-win_x64.msi       或者更改启动器的分辨率设置解决

**Comment by pysio2007** [comment]
这一般是由错误的分辨率设置，或者JAVA未能识别到正确的分辨率导致的，可以尝试使用Zulu JDK:https://cdn.azul.com/zulu/bin/zulu8.66.0.15-ca-jdk8.0.352-win_x64.msi       或者更改启动器的分辨率设置解决

**Comment by Jrojro728** [comment]
bruh，是官方启动器的java问题，没事了
