### ISSUE TITLE
3.03 crashes my minecraft - Discord Tickets 18

### ISSUE THREAD

**Issue by pysio2007** [ItzGreenCat/Antimony-SkyBlock#24]
3.03 crashes my minecraft
crash report: https://hst.sh/adagawiroz

**Comment by Jrojro728** [comment]
他把那几行给注释了啊

**Comment by Jrojro728** [comment]
反正我刚刚测试时没有出现你说的问题也。

**Comment by pysio2007** [comment]
![image](https://user-images.githubusercontent.com/71202163/200162958-01aaa5e9-ab28-45b7-b221-a88ea8b128c7.png)

**Comment by pysio2007** [comment]
Discord的工单

**Comment by pysio2007** [comment]
Discord Cannot be reproduced
关单了

**Comment by Jrojro728** [comment]
hmm，看起来像是我的错，是不规范的json格式异常

**Comment by Jrojro728** [comment]
wait，3.0.3不是禁用了ItemTranslate吗怎么还崩了

**Comment by pysio2007** [comment]
让我看看记录 绿猫改了啥

**Comment by pysio2007** [comment]
![image](https://user-images.githubusercontent.com/71202163/200161761-96f5b8bc-4b92-4220-b338-d1c32d028028.png)

**Comment by pysio2007** [comment]
。。。。。。。。。
