### ISSUE TITLE
和MelodySky冲突

### ISSUE THREAD

**Issue by dyorangeLOL** [ItzGreenCat/Antimony-SkyBlock#26]
呜呜呜呜呜呜呜呜

**Comment by pysio2007** [comment]
#13

**Comment by pysio2007** [comment]
给一下游戏日志或者视频。

**Comment by dyorangeLOL** [comment]
> 给一下游戏日志或者视频。

没日志 latest也是上一次的

**Comment by dyorangeLOL** [comment]
![image](https://user-images.githubusercontent.com/109525416/200275340-bddd9baa-5717-4e77-9f23-035ed58b406a.png)
一直卡在这

**Comment by pysio2007** [comment]
[Log1.md](https://github.com/ItzGreenCat/Antimony-SkyBlock/files/9950112/Log1.md)

**Comment by pysio2007** [comment]
@NMSLAndy 过来处理一下

**Comment by Jrojro728** [comment]
emm为什么日志里面看起来像是java版本问题呢？指定了java17

**Comment by pysio2007** [comment]
@Jrojro728 最后一次启动是JAVA8
[17:28:01.481] [Java] 选定的 Java：Java 8 (8.0.60)，64 位：D:\MCLDownload\ext\jre-v64-170307\jre8\bin\     
JAVA17启动被启动器阻止了

**Comment by dyorangeLOL** [comment]
> 怎么最后几行日志说游戏后台有日志了呢？不确定。而且好像你才等了几秒钟 @dyorangeLOL

等了10分钟。

**Comment by dyorangeLOL** [comment]
> 怎么最后几行日志说游戏后台有日志了呢？不确定。

后台没日志 日志是上次启动的

**Comment by pysio2007** [comment]
此ISS转到我的存储库，我进行修复，方便管理。https://github.com/pysio2007/Pysio_ALL_ISS

**Comment by pysio2007** [comment]
https://github.com/pysio2007/Pysio_ALL_ISS/issues/1
