### ISSUE TITLE
Auto kill 无法找到对应物品

### ISSUE THREAD

**Issue by Rryousa** [ItzGreenCat/Antimony-SkyBlock#27]
如题，请问该如何填右键物品名称
![9TQ@494~Y2Z~`DFTCTN%IDG](https://user-images.githubusercontent.com/117650269/200311500-a9231dbb-40ef-4fbf-911f-b72c3fb9bce4.png)
例如这个 我不论是Heroic Hyperion、Hyperion  还是 skyblock:HYPERION都没反应

**Comment by pysio2007** [comment]
@ItzGreenCat

**Comment by Rryousa** [comment]
准确来说在autofishing的时候才找不到

**Comment by Rryousa** [comment]
![1](https://user-images.githubusercontent.com/117650269/200810905-79d2df41-6a41-4456-9471-a6fbe9892c12.png)
![2](https://user-images.githubusercontent.com/117650269/200810930-b8ac3757-e003-451e-a07c-7fb26246e5d2.png)

**Comment by ItzGreenCat** [comment]
配置填写错误，请填写"Hyperion"或者部分名字如"Hyper",请确保未使用任何自定义名称模组

**Comment by Rryousa** [comment]
oh我写hyper就好了，谢谢绿@^@
