### ISSUE TITLE
寻路杀人事件 -QECN 

### ISSUE THREAD

**Issue by pysio2007** [ItzGreenCat/Antimony-SkyBlock#32]
![YI%BVU 941IIJM)HPC@42UD](https://user-images.githubusercontent.com/71202163/201084683-eb6f88f4-d25e-4352-a02a-2baf7c2fc60d.png)
RT，转自群友

**Comment by Qewide** [comment]
为了杀一个悬崖边的狼而抛弃我的生命

**Comment by SGShangGu** [comment]
绷不住了
Unbengable

**Comment by ItzGreenCat** [comment]
特性，不知道什么时候修复 (
