### ISSUE TITLE
代码库回滚公告

### ISSUE THREAD

**Issue by pysio2007** [ItzGreenCat/Antimony-SkyBlock#33]
因3.0.6 卡顿严重 回滚代码到 43eeef4
@Jrojro728 @pysio2007 @ItzGreenCat

**Comment by pysio2007** [comment]
d5e6d3f017f14b8b19120966a4f06e2400d0494b 这次提交有人没删代理 :( @ItzGreenCat

**Comment by Jrojro728** [comment]
额，这次提交怎么用上了shadow(

**Comment by ItzGreenCat** [comment]
我换的shadow，需要打包一些东西
