### ISSUE TITLE
建议删除ViaVerson

### ISSUE THREAD

**Issue by MatrixU5er** [ItzGreenCat/Antimony-SkyBlock#34]
一个专注于hypixel skyblock ForgeMod 需要内置ViaForge 谁会使用Viaverson去游玩hypixel呢? 
如果需要建议他们自己下载ViaForge而不是在这个mod里内置!
这不仅增大了Mod占用内存 并且可能导致客户端卡顿 或者降低FPS

**Comment by pysio2007** [comment]
此MOD不在只用于Hypixel SKyblock 最新的Readme.md也有说明。（之前改过，但是 #33 回滚掉了
