### ISSUE TITLE
开了SecretBot进地牢闪退

### ISSUE THREAD

**Issue by Rryousa** [ItzGreenCat/Antimony-SkyBlock#36]
[错误报告-2022-11-19_23.04.00.zip](https://github.com/ItzGreenCat/Antimony-SkyBlock/files/10047264/-2022-11-19_23.04.00.zip)
如题

**Comment by ItzGreenCat** [comment]
是否进入F5
如进入F5崩溃为LividESP导致，请关闭LividESP
LividESP将会在下个版本修复
