### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by GeorgieMaxGotWiped** [ItzGreenCat/Antimony-SkyBlock#38]
1.autofish添加锁物品栏槽（防止误触鼠标滚轮导致钓鱼中断）
2.AutoUse/Autokillworm添加多个进程同时进行（钓腐化虫，打es等）
3.添加Nuker
4.Antimony Rank系统

**Comment by pysio2007** [comment]
Antimony Rank系统 -BlackList系统目前提供娱乐性rank，加入rank系统还会造成显示冲突。

**Comment by ItzGreenCat** [comment]
Nuker已经完成
其他问题对应功能暂时不考虑添加
