### ISSUE TITLE
Some Suggestions which may be of help.整点有帮助的建议

### ISSUE THREAD

**Issue by SGShangGu** [ItzGreenCat/Antimony-SkyBlock#40]
1.给更多的功能添加切换世界自动关闭选项，最好是作为单项功能的clickgui设定出现... 比如Autouse，killaura等等
1.Add Turn-off-on-world-swithc function to more functions. It will be better if we can set whether using this for single function in click gui .
2.为DroppedItemESP添加更多更多颜色，以适应不同岛屿的色调。
2.Add more Colors to DroppedItemESP to deal with different hues on different islands.
3.PlayerFinder有时候会把哥布林之类的很多东西都识别为玩家...在哥布林洞简直是瞎了。
3.PlayerFinder will sometimes highlight goblins like players, which makes me Blinded in Golbin Burrow...

**Comment by pysio2007** [comment]
@ItzGreenCat

**Comment by Qewide** [comment]
Keybinds 添加搜索栏

**Comment by SGShangGu** [comment]
Keybinds添加分类

**Comment by Qewide** [comment]
AutoClicker 添加自定义cps

**Comment by pysio2007** [comment]
切换大厅时关闭杀戮光环 -直播间

**Comment by ItzGreenCat** [comment]
第一项暂时不考虑，第二三项已经修复，切换大厅关闭killaura已经修复，autoClicker与keybind搜索栏已经添加到计划列表，请等待后续更新
