### ISSUE TITLE
来自12.11晚QQ聊天

### ISSUE THREAD

**Issue by SGShangGu** [ItzGreenCat/Antimony-SkyBlock#50]
GreenCat 18:45:41
3.5版本我就没写weakling判定

Shang_gu 18:45:44

Shang_gu 18:45:46
ok

GreenCat 18:45:49
忘写了

Shang_gu 18:46:05
能不能auto leave显示离开时的player名单啊

**Comment by SGShangGu** [comment]
autouse在使用其他UI界面输入文字时会触发
（恶性示例：你AH输入物品名给你传送了）

**Comment by ItzGreenCat** [comment]
已经修复
