### ISSUE TITLE
为auto use的计时器添加一位小数位

### ISSUE THREAD

**Issue by SGShangGu** [ItzGreenCat/Antimony-SkyBlock#54]
rt
有两个意义：
第一满足0.x秒间隔的爆发式使用需求
第二 将auto use设置为24.2s在矮人矿洞约等于自动激活挖矿技能 目前只能上取整设置为25s，影响速度
（冷却120s 如果有sky mall激活是96s 最大公因数为24s 为了稳妥应向上取，理想是24.2s 但是实际设为25s）

**Comment by ItzGreenCat** [comment]
少一秒问题不大(
