### ISSUE TITLE
Slug Fishing Issue - ticket number 22;discord- 5erend1p1ty#5445

### ISSUE THREAD

**Issue by boosic** [ItzGreenCat/Antimony-SkyBlock#62]
There are some problems with the slugfish mode in the Autofish function.it should finish when the fish is hooked 30 seconds later, not when the rod is thrown for 30 seconds

这项功能应该在抛竿30s后的鱼上钩时进行收杆，而不是抛竿30s时直接进行收杆

**Comment by pysio2007** [comment]
that's not a problem
Please turn off the "automatic re-throwing" function.(自动重抛竿)
You can turn it off in the configuration interface of AutoFish.
