### ISSUE TITLE
Discord Suggestion - Spiral ESP for Dillo

### ISSUE THREAD

**Issue by boosic** [ItzGreenCat/Antimony-SkyBlock#63]
Discord requester - Djgun_Official#6870

Message - I hope to add the feature to find throne and spiral for dillo mining in crystal hollow, because using lanternESP is very inefficient: 

https://www.bilibili.com/video/BV1w84y1r7Ye

**Comment by ItzGreenCat** [comment]
This feature has been added in version 3.9, please wait for the update.
