### ISSUE TITLE
PlayerFinder Issues

### ISSUE THREAD

**Issue by Tr4velt0Here** [ItzGreenCat/Antimony-SkyBlock#75]
![image](https://user-images.githubusercontent.com/87561321/212249603-ae9b0aa6-3301-4f8d-b701-ef40e64a4325.png)

**Comment by Tr4velt0Here** [comment]
and this
![Uploading image.png…]()

**Comment by Tr4velt0Here** [comment]
![image](https://user-images.githubusercontent.com/87561321/212253903-0cbf02b2-cfdd-4839-9b5f-d8991c54c392.png)

**Comment by Tr4velt0Here** [comment]
![image](https://user-images.githubusercontent.com/87561321/212271131-186a3f6f-2522-4976-af56-d45250c6beeb.png)

**Comment by Tr4velt0Here** [comment]
![image](https://user-images.githubusercontent.com/87561321/212285260-1b1e3c5a-3028-4105-adbf-d585c5d13017.png)

**Comment by pysio2007** [comment]
FIX
