### ISSUE TITLE
2.0.9.4 InstantSwitch按键设置导致崩溃

### ISSUE THREAD

**Issue by sui-feng-cb** [ItzGreenCat/Antimony-SkyBlock#8]
InstantSwitch的按键设置为鼠标左键、鼠标右键或鼠标中键时导致游戏崩溃，通过在options.txt中修改按键设置才可再次进入游戏

**Comment by pysio2007** [comment]
因某只猫 没写注释 我暂时无法修复 等待某只猫进行修复

**Comment by ItzGreenCat** [comment]
有没有一种可能，我可以开发一个叫MouseISwitch的功能来使用鼠标触发InstantSwitch
