### ISSUE TITLE
跨版本回弹问题

### ISSUE THREAD

**Issue by trytorat** [ItzGreenCat/Antimony-SkyBlock#81]
1.8.9用了跨版本之后进1.12.2服务器会回弹
不能用Antimony出击hyt了 (

**Comment by Jrojro728** [comment]
调去1.12.2试试

**Comment by ItzGreenCat** [comment]
> 1.8.9用了跨版本之后进1.12.2服务器会回弹
> 不能用Antimony出击hyt了 (

那是被anticheat拦下来了
不行就试试更高的版本，不过我记得hyt是1.8.9也能进的，之前我用1.8.9进去过
