### ISSUE TITLE
me.greencat.lwebus包找不到

### ISSUE THREAD

**Issue by catandA** [ItzGreenCat/Antimony-SkyBlock#90]
5.0版本引入的Event和ReflectionlessEventHandler这两个类好像缺失了导致无法编译
依赖看起来也没变
绿猫猫是专门不开源的还是忘了git commit

**Comment by pysio2007** [comment]
f2eac7e7a5495bfe2d513bd1471fc024f613f847 已在此次提交修复 项目同时宣告停止维护

**Comment by pysio2007** [comment]
![image](https://github.com/ItzGreenCat/Antimony-SkyBlock/assets/71202163/fd2b46fd-a4b4-4436-93d8-e8718bfc47e1)
来一点喜闻乐见的全绿截图
